var locations = [
  {
    'name': "Base Camp Brewery",
    'area': "se",
    'hours': {
      'friday-end': "1800",
      'friday-start': "1500",
      'monday-end': "2200",
      'monday-start': "1200",
      'saturday-end': "1500",
      'saturday-start': "1200",
      'sunday-end': "1500",
      'sunday-start': "1200",
      'thursday-end': "1800",
      'thursday-start': "1500",
      'tuesday-end': "1800",
      'tuesday-start': "1500",
      'wednesday-end': "1800",
      'wednesday-start': "1500"
    },
    'description': "$1 off pints",
    'link': "https://basecampbrewingco.com/",
    'pricing': "medium",
    'phone-number': "503-477-7479",
    'address': "930 SE Oak St, Portland, OR 97214",
    'other-amenities': ['outdoor-seating', 'trivia'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Bartini",
    'area': "nw",
    'hours': {
      'monday-start': "1600",
      'monday-end': "1830",
      'tuesday-start': "1600",
      'tuesday-end': "1830",
      'wednesday-start': "1600",
      'wednesday-end': "1830",
      'thursday-start': "1600",
      'thursday-end': "1830",
      'friday-start': "1600",
      'friday-end': "1830",
      'saturday-start': "1600",
      'saturday-end': "1830",
      'sunday-start': "1600",
      'sunday-end': "2300",
    },
    'description': "About 50% off food, $4-$6 drinks.",
    'link': "http://www.bartinipdx.com/",
    'pricing': "medium",
    'phone-number': "503-224-7919",
    'address': "2108 NW Glisan St, Portland, OR 97210",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Swine Moonshine and Whiskey Bar",
    'area': "nw",
    'hours': {
      'monday-start': "1500",
      'monday-end': "1830",
      'tuesday-start': "1500",
      'tuesday-end': "1830",
      'wednesday-start': "1500",
      'wednesday-end': "1830",
      'thursday-start': "1500",
      'thursday-end': "1830",
      'friday-start': "1500",
      'friday-end': "1830",
      'saturday-start': "1500",
      'saturday-end': "1830",
      'sunday-start': "1500",
      'sunday-end': "1830",
    },
    'description': "Food, $7 Cocktails, $6 well, $4 drafts",
    'link': "http://www.swankandswine.com/happy-hour/",
    'pricing': "medium",
    'phone-number': "503-943 5844",
    'address': "808 SW Taylor St, Portland, OR 97205",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Touche",
    'area': "nw",
    'hours': {
      'monday-start': "1600",
      'monday-end': "1830",
      'tuesday-start': "1600",
      'tuesday-end': "1830",
      'wednesday-start': "1600",
      'wednesday-end': "1830",
      'thursday-start': "1600",
      'thursday-end': "1830",
      'friday-start': "1600",
      'friday-end': "1830",
      'saturday-start': "1600",
      'saturday-end': "1830",
      'sunday-start': "1600",
      'sunday-end': "2630",
    },
    'description': "$3-$7 food, $4 wells, $6 wine, $1 off beer",
    'link': "http://touchepdx.com/happy-hour/",
    'pricing': "medium",
    'phone-number': "(503) 221-1150",
    'address': "1425 NW Glisan St, Portland, OR 97209",
    'other-amenities': ['outdoor-seating', 'games', 'vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Pope House Bourbon Lounge",
    'area': "nw",
    'hours': {
      'monday-start': "1600",
      'monday-end': "2400",
      'tuesday-start': "1600",
      'tuesday-end': "1900",
      'wednesday-start': "1600",
      'wednesday-end': "1900",
      'thursday-start': "1600",
      'thursday-end': "1900",
      'friday-start': "1600",
      'friday-end': "1900",
      'saturday-start': "1600",
      'saturday-end': "1900",
      'sunday-start': "1600",
      'sunday-end': "1900",
    },
    'description': "$1 off drinks, food specials",
    'link': "http://www.popehouselounge.com/new-page/",
    'pricing': "medium",
    'phone-number': "(503) 222-1056",
    'address': "2075 NW Glisan St, Portland, OR 97209",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Kell's Brew Pub",
    'area': "nw",
    'hours': {
      'monday-start': "1500",
      'monday-end': "1800",
      'tuesday-start': "1500",
      'tuesday-end': "1800",
      'wednesday-start': "1500",
      'wednesday-end': "1800",
      'thursday-start': "1500",
      'thursday-end': "1800",
      'friday-start': "1500",
      'friday-end': "1800",
      'saturday-start': "",
      'saturday-end': "",
      'sunday-start': "1600",
      'sunday-end': "2400",
    },
    'description': "$6 wine, $7 mule, $3.50 beers, $3-7 food",
    'link': "http://www.kellsbrewpub.com/happy-hour",
    'pricing': "medium",
    'phone-number': "(503) 719-7175",
    'address': "210 NW 21st Ave, Portland, OR 97209",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Cruzroom",
    'area': "ne",
    'hours': {
      'monday-start': "1600",
      'monday-end': "1830",
      'tuesday-start': "1600",
      'tuesday-end': "1830",
      'wednesday-start': "1600",
      'wednesday-end': "1830",
      'thursday-start': "1600",
      'thursday-end': "1830",
      'friday-start': "1600",
      'friday-end': "1830",
      'saturday-start': "1600",
      'saturday-end': "1830",
      'sunday-start': "1600",
      'sunday-end': "1830",
    },
    'description': "$2.50 tacos, $5 House infused liquor.",
    'link': "http://cruzroom.com/",
    'pricing': "medium",
    'phone-number': "(503) 208-3483",
    'address': "2338 NE Alberta St, Portland, OR 97211",
    'other-amenities': ['trivia', 'vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Swift Lounge",
    'area': "ne",
    'hours': {
      'monday-start': "1600",
      'monday-end': "2000",
      'tuesday-start': "1600",
      'tuesday-end': "2000",
      'wednesday-start': "1600",
      'wednesday-end': "2000",
      'thursday-start': "1600",
      'thursday-end': "2000",
      'friday-start': "1600",
      'friday-end': "2000",
      'saturday-start': "1600",
      'saturday-end': "2000",
      'sunday-start': "1600",
      'sunday-end': "2600",
    },
    'description': "$3-$5 food, $1 off mason jar drinks",
    'link': "http://www.swiftloungepdx.com/swiftloungemenu/",
    'pricing': "medium",
    'phone-number': "(503) 288-3333",
    'address': "1932 NE Broadway St, Portland, OR 97232",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Saucebox",
    'area': "sw",
    'hours': {
      'monday-start': "",
      'monday-end': "",
      'tuesday-start': "1630",
      'tuesday-end': "1830",
      'wednesday-start': "1630",
      'wednesday-end': "1830",
      'thursday-start': "1630",
      'thursday-end': "1830",
      'friday-start': "1630",
      'friday-end': "1830",
      'saturday-start': "1700",
      'saturday-end': "1830",
      'sunday-start': "",
      'sunday-end': "",
    },
    'description': "$2-$6 snacks, $4-$6 drinks",
    'link': "http://www.saucebox.com/happy-hour/",
    'pricing': "low",
    'phone-number': "(503) 241-3393",
    'address': "214 SW Broadway, Portland, OR 97205",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Lightning Will",
    'area': "nw",
    'hours': {
      'monday-start': "1700",
      'monday-end': "1900",
      'tuesday-start': "1700",
      'tuesday-end': "1900",
      'wednesday-start': "1700",
      'wednesday-end': "1900",
      'thursday-start': "1700",
      'thursday-end': "1900",
      'friday-start': "",
      'friday-end': "",
      'saturday-start': "",
      'saturday-end': "",
      'sunday-start': "",
      'sunday-end': "",
    },
    'description': "$1 off food",
    'link': "http://www.lightningwill.com/menu.html",
    'pricing': "medium",
    'phone-number': "(503) 327-8203",
    'address': "305 NW 21st Ave, Portland, OR 97209",
    'other-amenities': ['outdoor-seating', 'games', 'gluten-free-options'],
    'has-drink': false,
    'has-food': true,
  },
  {
    'name': "Parkside",
    'area': "n",
    'hours': {
      'monday-start': "1100",
      'monday-end': "2200",
      'tuesday-start': "",
      'tuesday-end': "",
      'wednesday-start': "",
      'wednesday-end': "",
      'thursday-start': "",
      'thursday-end': "",
      'friday-start': "",
      'friday-end': "",
      'saturday-start': "",
      'saturday-end': "",
      'sunday-start': "",
      'sunday-end': "",
    },
    'description': "$4 beer and well, $5 wine",
    'link': "http://www.portlandparkside.com/",
    'pricing': "medium",
    'phone-number': "(503) 719-6826",
    'address': "2135 N Willis Blvd, Portland, OR 97217",
    'other-amenities': ['outdoor-seating', 'games', 'trivia'],
    'has-drink': true,
    'has-food': false,
  },
  {
    'name': "Rock Bottom Brewery",
    'area': "sw",
    'hours': {
      'monday-start': "1500",
      'monday-end': "1830",
      'tuesday-start': "1500",
      'tuesday-end': "1830",
      'wednesday-start': "1500",
      'wednesday-end': "1830",
      'thursday-start': "1500",
      'thursday-end': "1830",
      'friday-start': "1500",
      'friday-end': "1830",
      'saturday-start': "2200",
      'saturday-end': "2400",
      'sunday-start': "2100",
      'sunday-end': "2400",
    },
    'description': "$5-7 apps, $2 off drinks",
    'link': "http://menu.rockbottom.com/portland",
    'pricing': "medium",
    'phone-number': "(503) 796-2739",
    'address': "206 SW Morrison St, Portland, OR 97204",
    'other-amenities': ['outdoor-seating', 'gluten-free-options', 'games'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Punch Bowl Social",
    'area': "nw",
    'hours': {
      'monday-start': "1500",
      'monday-end': "1800",
      'tuesday-start': "1500",
      'tuesday-end': "1800",
      'wednesday-start': "1500",
      'wednesday-end': "1800",
      'thursday-start': "1500",
      'thursday-end': "1800",
      'friday-start': "1500",
      'friday-end': "1800",
      'saturday-start': "1500",
      'saturday-end': "1800",
      'sunday-start': "1500",
      'sunday-end': "1800",
    },
    'description': "$2 - $6 food, $3 - $7 drinks",
    'link': "http://www.punchbowlsocial.com/location/portland",
    'pricing': "medium",
    'phone-number': "(503) 334-0360",
    'address': "340 SW Morrison St, Portland, OR 97204",
    'other-amenities': ['outdoor-seating', 'games', 'karaoke', 'vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Santa Fe Taqueria",
    'area': "nw",
    'hours': {
      'monday-start': "2300",
      'monday-end': "2400",
      'tuesday-start': "2300",
      'tuesday-end': "2400",
      'wednesday-start': "2300",
      'wednesday-end': "2400",
      'thursday-start': "2300",
      'thursday-end': "2400",
      'friday-start': "2300",
      'friday-end': "2400",
      'saturday-start': "2300",
      'saturday-end': "2400",
      'sunday-start': "2300",
      'sunday-end': "2400",
    },
    'description': "50% off food menu",
    'link': "http://www.santafetaqueria.com/index.php/menu",
    'pricing': "low",
    'phone-number': "(503) 220-0406",
    'address': "831 NW 23rd Ave, Portland, OR 97210",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': false,
    'has-food': true,
  },
  {
    'name': "Pearl Tavern",
    'area': "sw",
    'hours': {
      'monday-start': "1500",
      'monday-end': "1800",
      'tuesday-start': "1500",
      'tuesday-end': "1800",
      'wednesday-start': "1500",
      'wednesday-end': "1800",
      'thursday-start': "1500",
      'thursday-end': "1800",
      'friday-start': "1500",
      'friday-end': "1800",
      'saturday-start': "1500",
      'saturday-end': "1800",
      'sunday-start': "1500",
      'sunday-end': "1800",
    },
    'description': "$4 - $10 food, $6 - $8 cocktails",
    'link': "http://pearltavernpdx.com/wp-content/uploads/2017/05/Happy-Hour-5.4.17-1.pdf",
    'pricing': "high",
    'phone-number': "(503) 954-3796",
    'address': "231 NW 11th Ave, Portland, OR 97209",
    'other-amenities': ['vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Headwaters",
    'area': "sw",
    'hours': {
      'monday-start': "1400",
      'monday-end': "1800",
      'tuesday-start': "1400",
      'tuesday-end': "1800",
      'wednesday-start': "1400",
      'wednesday-end': "1800",
      'thursday-start': "1400",
      'thursday-end': "1800",
      'friday-start': "1400",
      'friday-end': "1800",
      'saturday-start': "2200",
      'saturday-end': "2400",
      'sunday-start': "2200",
      'sunday-end': "2400",
    },
    'description': "$7 - $9 fancy food, $5 cocktails",
    'link': "http://www.headwaterspdx.com/s/Happy-Hour-41517-1-xces.pdf",
    'pricing': "high",
    'phone-number': "(503) 790-7752",
    'address': "1001 SW Broadway, Portland, OR 97205",
    'other-amenities': [''],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Shift Drinks",
    'area': "sw",
    'hours': {
      'monday-start': "1600",
      'monday-end': "2630",
      'tuesday-start': "1600",
      'tuesday-end': "2630",
      'wednesday-start': "1600",
      'wednesday-end': "2630",
      'thursday-start': "1600",
      'thursday-end': "2630",
      'friday-start': "1600",
      'friday-end': "2630",
      'saturday-start': "1600",
      'saturday-end': "2630",
      'sunday-start': "1600",
      'sunday-end': "2630",
    },
    'description': "Cheaper smaller portions of usually expensive food",
    'link': "https://www.scribd.com/document/348549641/Shift-Drinks-Happy-Hour-Menu-05-16-17",
    'pricing': "medium",
    'phone-number': "(503) 922-3933",
    'address': "1200 SW Morrison St, Portland, OR 97205",
    'other-amenities': ['vegan-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Red Star Tavern",
    'area': "sw",
    'hours': {
      'monday-start': "1600",
      'monday-end': "1900",
      'tuesday-start': "1600",
      'tuesday-end': "1900",
      'wednesday-start': "1600",
      'wednesday-end': "1900",
      'thursday-start': "1600",
      'thursday-end': "1900",
      'friday-start': "1600",
      'friday-end': "1900",
      'saturday-start': "1600",
      'saturday-end': "1900",
      'sunday-start': "1600",
      'sunday-end': "1900",
    },
    'description': "Happy hour food ONLY, $2 - $6",
    'link': "http://www.redstartavern.com/menus/menus.htm",
    'pricing': "medium",
    'phone-number': "(503) 222-0005",
    'address': "503 SW Alder St, Portland, OR 97204",
    'other-amenities': ['gluten-free-options', 'vegan-options'],
    'has-drink': false,
    'has-food': true,
  },
  {
    'name': "Roadside Attraction",
    'area': "se",
    'hours': {
      'monday-start': "1500",
      'monday-end': "1800",
      'tuesday-start': "1500",
      'tuesday-end': "1800",
      'wednesday-start': "1500",
      'wednesday-end': "1800",
      'thursday-start': "1500",
      'thursday-end': "1800",
      'friday-start': "1500",
      'friday-end': "1800",
      'saturday-start': "1500",
      'saturday-end': "1800",
      'sunday-start': "1500",
      'sunday-end': "1800",
    },
    'description': "$3 wine, $3 microbrews, $1.50 domestics",
    'link': "https://www.yelp.com/biz/roadside-attraction-portland-2",
    'pricing': "low",
    'phone-number': "(503) 233-0743",
    'address': "1000 SE 12th Ave, Portland, OR 97214",
    'other-amenities': ['outdoor-seating', 'games'],
    'has-drink': true,
    'has-food': false,
  },
  {
    'name': "Voicebox",
    'area': "se",
    'hours': {
      'monday-start': "1600",
      'monday-end': "2400",
      'tuesday-start': "1600",
      'tuesday-end': "1900",
      'wednesday-start': "1600",
      'wednesday-end': "2400",
      'thursday-start': "1600",
      'thursday-end': "1900",
      'friday-start': "1600",
      'friday-end': "1900",
      'saturday-start': "1600",
      'saturday-end': "1900",
      'sunday-start': "1600",
      'sunday-end': "1900",
    },
    'description': "$1 off drinks, $6 per person karaoke",
    'link': "http://voiceboxkaraoke.com/locations/southeast-portland/",
    'pricing': "medium",
    'phone-number': "(503) 303-8220",
    'address': "734 SE 6th Ave, Portland, Oregon 97214",
    'other-amenities': ['karaoke'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Aalto Lounge",
    'area': "se",
    'hours': {
      'monday-start': "1700",
      'monday-end': "1900",
      'tuesday-start': "1700",
      'tuesday-end': "1900",
      'wednesday-start': "1700",
      'wednesday-end': "1900",
      'thursday-start': "1700",
      'thursday-end': "1900",
      'friday-start': "1700",
      'friday-end': "1900",
      'saturday-start': "1700",
      'saturday-end': "1900",
      'sunday-start': "1700",
      'sunday-end': "1900",
    },
    'description': "$3 food and cocktails, $10 bottles of wine, $9 - $12 beer buckets",
    'link': "http://www.aaltolounge.com/happy-hour-menu/",
    'pricing': "low",
    'phone-number': "(503) 235-6041",
    'address': "3356 SE Belmont St Portland, OR, 97214",
    'other-amenities': ['outdoor-seating', 'vegan-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Frontier Public House",
    'area': "far",
    'hours': {
      'monday-start': "1500",
      'monday-end': "1800",
      'tuesday-start': "1500",
      'tuesday-end': "1800",
      'wednesday-start': "1500",
      'wednesday-end': "1800",
      'thursday-start': "1500",
      'thursday-end': "1800",
      'friday-start': "1500",
      'friday-end': "1800",
      'saturday-start': "1500",
      'saturday-end': "1800",
      'sunday-start': "1500",
      'sunday-end': "1800",
    },
    'description': "$2 off all menu items, $4 well drinks, $2 pint of Rainier, $3.50 house wines.",
    'link': "http://www.frontierpublichouse.com/menu.html",
    'pricing': "high",
    'phone-number': "(360) 718-2768",
    'address': "4909 NE Hazel Dell Ave, Vancouver, WA 98663",
    'other-amenities': ['outdoor-seating'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Jake's Grill",
    'area': "sw",
    'hours': {
      'monday-start': "1500",
      'monday-end': "1800",
      'tuesday-start': "1500",
      'tuesday-end': "1800",
      'wednesday-start': "1500",
      'wednesday-end': "1800",
      'thursday-start': "1500",
      'thursday-end': "1800",
      'friday-start': "1500",
      'friday-end': "1800",
      'saturday-start': "1300",
      'saturday-end': "1800",
      'sunday-start': "1500",
      'sunday-end': "2300",
    },
    'description': "$4 well liquor and draught microbrews, $6 Salmon Creek Cabernet and Chardonnay, $3 - $9 food specials.",
    'link': "http://menus.mccormickandschmicks.com/JKGR/JKGR-Happy.pdf",
    'pricing': "high",
    'phone-number': "(503) 220-1850",
    'address': "Sentinel Hotel, 611 SW 10th Ave, Portland, OR 97205",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': true,
    'has-food': true,
  },
  {
    'name': "Crush",
    'area': "se",
    'hours': {
      'monday-start': "1500",
      'monday-end': "2400",
      'tuesday-start': "1500",
      'tuesday-end': "1900",
      'wednesday-start': "1500",
      'wednesday-end': "1900",
      'thursday-start': "1500",
      'thursday-end': "1900",
      'friday-start': "1500",
      'friday-end': "1900",
      'saturday-start': "1500",
      'saturday-end': "1900",
      'sunday-start': "1500",
      'sunday-end': "1900",
    },
    'description': "$2.50 PBR, $4.50 microbrews, $4 wells, $5 - $6.50 specialty drinks.  $4 - $7.50 food specials.",
    'link': "http://www.crushbar.com/happy-hour.html",
    'pricing': "low",
    'phone-number': "(503) 235-8150",
    'address': "1400 SE Morrison St. Portland, OR 97214",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options', 'trivia', 'games'],
    'has-drink': true,
    'has-food': true,
  }
];
