{
  'name': "Base Camp Brewery",
  'area': "se",
  'hours': {
    'friday-end': "6",
    'friday-start': "3",
    'monday-end': "10",
    'monday-start': "0",
    'saturday-end': "3",
    'saturday-start': "0",
    'sunday-end': "3",
    'sunday-start': "0",
    'thursday-end': "6",
    'thursday-start': "3",
    'tuesday-end': "6",
    'tuesday-start': "3",
    'wednesday-end': "6",
    'wednesday-start': "3"
  }
  'description': "$1 off pints",
  'link': "https://basecampbrewingco.com/",
  'pricing': "medium",
  'phone-number': "503-477-7479",
  'address': "930 SE Oak St, Portland, OR 97214",
  'other-amenities': ['outdoor-seating', 'trivia'],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "Bartini",
  'area': "nw",
  'hours': {
    'monday-start': "4",
    'monday-end': "6",
    'tuesday-start': "4",
    'tuesday-end': "6",
    'wednesday-start': "4"
    'wednesday-end': "6",
    'thursday-start': "4",
    'thursday-end': "6",
    'friday-start': "4",
    'friday-end': "6",
    'saturday-start': "4",
    'saturday-end': "6",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "About 50% off food, $4-$6 drinks.",
  'link': "http://www.bartinipdx.com/",
  'pricing': "medium",
  'phone-number': "503-224-7919",
  'address': "2108 NW Glisan St, Portland, OR 97210",
  'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "",
  'area': "",
  'hours': {
    'monday-start': "",
    'monday-end': "",
    'tuesday-start': "",
    'tuesday-end': "",
    'wednesday-start': ""
    'wednesday-end': "",
    'thursday-start': "",
    'thursday-end': "",
    'friday-start': "",
    'friday-end': "",
    'saturday-start': "",
    'saturday-end': "",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "",
  'link': "",
  'pricing': "",
  'phone-number': "",
  'address': "",
  'other-amenities': [''],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "",
  'area': "",
  'hours': {
    'monday-start': "",
    'monday-end': "",
    'tuesday-start': "",
    'tuesday-end': "",
    'wednesday-start': ""
    'wednesday-end': "",
    'thursday-start': "",
    'thursday-end': "",
    'friday-start': "",
    'friday-end': "",
    'saturday-start': "",
    'saturday-end': "",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "",
  'link': "",
  'pricing': "",
  'phone-number': "",
  'address': "",
  'other-amenities': [''],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "",
  'area': "",
  'hours': {
    'monday-start': "",
    'monday-end': "",
    'tuesday-start': "",
    'tuesday-end': "",
    'wednesday-start': ""
    'wednesday-end': "",
    'thursday-start': "",
    'thursday-end': "",
    'friday-start': "",
    'friday-end': "",
    'saturday-start': "",
    'saturday-end': "",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "",
  'link': "",
  'pricing': "",
  'phone-number': "",
  'address': "",
  'other-amenities': [''],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "",
  'area': "",
  'hours': {
    'monday-start': "",
    'monday-end': "",
    'tuesday-start': "",
    'tuesday-end': "",
    'wednesday-start': ""
    'wednesday-end': "",
    'thursday-start': "",
    'thursday-end': "",
    'friday-start': "",
    'friday-end': "",
    'saturday-start': "",
    'saturday-end': "",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "",
  'link': "",
  'pricing': "",
  'phone-number': "",
  'address': "",
  'other-amenities': [''],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "",
  'area': "",
  'hours': {
    'monday-start': "",
    'monday-end': "",
    'tuesday-start': "",
    'tuesday-end': "",
    'wednesday-start': ""
    'wednesday-end': "",
    'thursday-start': "",
    'thursday-end': "",
    'friday-start': "",
    'friday-end': "",
    'saturday-start': "",
    'saturday-end': "",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "",
  'link': "",
  'pricing': "",
  'phone-number': "",
  'address': "",
  'other-amenities': [''],
  'has-drink': "true",
  'has-food': "true",
},
