[
  {
    'name': "Base Camp Brewery",
    'area': "se",
    'hours': {
      'friday-end': "6",
      'friday-start': "3",
      'monday-end': "10",
      'monday-start': "0",
      'saturday-end': "3",
      'saturday-start': "0",
      'sunday-end': "3",
      'sunday-start': "0",
      'thursday-end': "6",
      'thursday-start': "3",
      'tuesday-end': "6",
      'tuesday-start': "3",
      'wednesday-end': "6",
      'wednesday-start': "3"
    }
    'description': "$1 off pints",
    'link': "https://basecampbrewingco.com/",
    'pricing': "medium",
    'phone-number': "503-477-7479",
    'address': "930 SE Oak St, Portland, OR 97214",
    'other-amenities': ['outdoor-seating', 'trivia'],
    'has-drink': "true",
    'has-food': "true",
  },
  {
    'name': "Bartini",
    'area': "nw",
    'hours': {
      'monday-start': "4",
      'monday-end': "6",
      'tuesday-start': "4",
      'tuesday-end': "6",
      'wednesday-start': "4"
      'wednesday-end': "6",
      'thursday-start': "4",
      'thursday-end': "6",
      'friday-start': "4",
      'friday-end': "6",
      'saturday-start': "4",
      'saturday-end': "6",
      'sunday-start': "4",
      'sunday-end': "11",
    }
    'description': "About 50% off food, $4-$6 drinks.",
    'link': "http://www.bartinipdx.com/",
    'pricing': "medium",
    'phone-number': "503-224-7919",
    'address': "2108 NW Glisan St, Portland, OR 97210",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': "true",
    'has-food': "true",
  },
  {
    'name': "Swine Moonshine and Whiskey Bar",
    'area': "nw",
    'hours': {
      'monday-start': "3",
      'monday-end': "6",
      'tuesday-start': "3",
      'tuesday-end': "6",
      'wednesday-start': "3"
      'wednesday-end': "6",
      'thursday-start': "3",
      'thursday-end': "6",
      'friday-start': "3",
      'friday-end': "6",
      'saturday-start': "3",
      'saturday-end': "6",
      'sunday-start': "3",
      'sunday-end': "6",
    }
    'description': "Food, $7 Cocktails, $6 well, $4 drafts",
    'link': "http://www.swankandswine.com/happy-hour/",
    'pricing': "medium",
    'phone-number': "503-943 5844",
    'address': "808 SW Taylor St, Portland, OR 97205",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': "true",
    'has-food': "true",
  },
  {
    'name': "Touche",
    'area': "nw",
    'hours': {
      'monday-start': "4",
      'monday-end': "6",
      'tuesday-start': "4",
      'tuesday-end': "6",
      'wednesday-start': "4"
      'wednesday-end': "6",
      'thursday-start': "4",
      'thursday-end': "6",
      'friday-start': "4",
      'friday-end': "6",
      'saturday-start': "4",
      'saturday-end': "6",
      'sunday-start': "4",
      'sunday-end': "20",
    }
    'description': "$3-$7 food, $4 wells, $6 wine, $1 off beer",
    'link': "http://touchepdx.com/happy-hour/",
    'pricing': "medium",
    'phone-number': "(503) 221-1150",
    'address': "1425 NW Glisan St, Portland, OR 97209",
    'other-amenities': ['outdoor-seating', 'games', 'vegan-options', 'gluten-free-options'],
    'has-drink': "true",
    'has-food': "true",
  },
  {
    'name': "Pope House Bourbon Lounge",
    'area': "nw",
    'hours': {
      'monday-start': "4",
      'monday-end': "12",
      'tuesday-start': "4",
      'tuesday-end': "7",
      'wednesday-start': "4"
      'wednesday-end': "7",
      'thursday-start': "4",
      'thursday-end': "7",
      'friday-start': "4",
      'friday-end': "7",
      'saturday-start': "4",
      'saturday-end': "7",
      'sunday-start': "4",
      'sunday-end': "7",
    }
    'description': "$1 off drinks, food specials",
    'link': "http://www.popehouselounge.com/new-page/",
    'pricing': "medium",
    'phone-number': "(503) 222-1056",
    'address': "2075 NW Glisan St, Portland, OR 97209",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': "true",
    'has-food': "true",
  },
  {
    'name': "Kell's Brew Pub",
    'area': "nw",
    'hours': {
      'monday-start': "3",
      'monday-end': "6",
      'tuesday-start': "3",
      'tuesday-end': "6",
      'wednesday-start': "3"
      'wednesday-end': "6",
      'thursday-start': "3",
      'thursday-end': "6",
      'friday-start': "3",
      'friday-end': "6",
      'saturday-start': "",
      'saturday-end': "",
      'sunday-start': "10",
      'sunday-end': "12",
    }
    'description': "$6 wine, $7 mule, $3.50 beers, $3-7 food",
    'link': "http://www.kellsbrewpub.com/happy-hour",
    'pricing': "medium",
    'phone-number': "(503) 719-7175",
    'address': "210 NW 21st Ave, Portland, OR 97209",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': "true",
    'has-food': "true",
  },
  {
    'name': "Cruzroom",
    'area': "ne",
    'hours': {
      'monday-start': "4",
      'monday-end': "6",
      'tuesday-start': "4",
      'tuesday-end': "6",
      'wednesday-start': "4"
      'wednesday-end': "6",
      'thursday-start': "4",
      'thursday-end': "6",
      'friday-start': "4",
      'friday-end': "6",
      'saturday-start': "4",
      'saturday-end': "6",
      'sunday-start': "4",
      'sunday-end': "6",
    }
    'description': "$2.50 tacos, $5 House infused liquor.",
    'link': "http://cruzroom.com/",
    'pricing': "medium",
    'phone-number': "(503) 208-3483",
    'address': "2338 NE Alberta St, Portland, OR 97211",
    'other-amenities': ['trivia', 'vegan-options', 'gluten-free-options'],
    'has-drink': "true",
    'has-food': "true",
  },
  {
    'name': "Swift Lounge",
    'area': "ne",
    'hours': {
      'monday-start': "4",
      'monday-end': "8",
      'tuesday-start': "4",
      'tuesday-end': "8",
      'wednesday-start': "4"
      'wednesday-end': "8",
      'thursday-start': "4",
      'thursday-end': "8",
      'friday-start': "4",
      'friday-end': "8",
      'saturday-start': "4",
      'saturday-end': "8",
      'sunday-start': "4",
      'sunday-end': "2",
    }
    'description': "$3-$5 food, $1 off mason jar drinks",
    'link': "http://www.swiftloungepdx.com/swiftloungemenu/",
    'pricing': "medium",
    'phone-number': "(503) 288-3333",
    'address': "1932 NE Broadway St, Portland, OR 97232",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': "true",
    'has-food': "true",
  },
  {
    'name': "Saucebox",
    'area': "sw",
    'hours': {
      'monday-start': "",
      'monday-end': "",
      'tuesday-start': "4",
      'tuesday-end': "6",
      'wednesday-start': "4"
      'wednesday-end': "6",
      'thursday-start': "4",
      'thursday-end': "6",
      'friday-start': "4",
      'friday-end': "6",
      'saturday-start': "5",
      'saturday-end': "6",
      'sunday-start': "",
      'sunday-end': "",
    }
    'description': "$2-$6 snacks, $4-$6 drinks",
    'link': "http://www.saucebox.com/happy-hour/",
    'pricing': "low",
    'phone-number': "(503) 241-3393",
    'address': "214 SW Broadway, Portland, OR 97205",
    'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
    'has-drink': "true",
    'has-food': "true",
  },
  {
    'name': "Lightning Will",
    'area': "nw",
    'hours': {
      'monday-start': "5",
      'monday-end': "7",
      'tuesday-start': "5",
      'tuesday-end': "7",
      'wednesday-start': "5"
      'wednesday-end': "7",
      'thursday-start': "5",
      'thursday-end': "7",
      'friday-start': "",
      'friday-end': "",
      'saturday-start': "",
      'saturday-end': "",
      'sunday-start': "",
      'sunday-end': "",
    }
    'description': "$1 off food",
    'link': "http://www.lightningwill.com/menu.html",
    'pricing': "medium",
    'phone-number': "(503) 327-8203",
    'address': "305 NW 21st Ave, Portland, OR 97209",
    'other-amenities': ['outdoor-seating', 'games', 'gluten-free-options'],
    'has-drink': "false",
    'has-food': "true",
  },
  {
    'name': "Parkside",
    'area': "n",
    'hours': {
      'monday-start': "0",
      'monday-end': "10",
      'tuesday-start': "",
      'tuesday-end': "",
      'wednesday-start': ""
      'wednesday-end': "",
      'thursday-start': "",
      'thursday-end': "",
      'friday-start': "",
      'friday-end': "",
      'saturday-start': "",
      'saturday-end': "",
      'sunday-start': "",
      'sunday-end': "",
    }
    'description': "$4 beer and well, $5 wine",
    'link': "http://www.portlandparkside.com/",
    'pricing': "medium",
    'phone-number': "(503) 719-6826",
    'address': "2135 N Willis Blvd, Portland, OR 97217",
    'other-amenities': ['outdoor-seating', 'games', 'trivia'],
    'has-drink': "true",
    'has-food': false,
  },
  {
    'name': "Rock Bottom Brewery",
    'area': "sw",
    'hours': {
      'monday-start': "3",
      'monday-end': "6",
      'tuesday-start': "3",
      'tuesday-end': "6",
      'wednesday-start': "3"
      'wednesday-end': "6",
      'thursday-start': "3",
      'thursday-end': "6",
      'friday-start': "3",
      'friday-end': "6",
      'saturday-start': "10",
      'saturday-end': "12",
      'sunday-start': "9",
      'sunday-end': "12",
    }
    'description': "$5-7 apps, $2 off drinks",
    'link': "http://menu.rockbottom.com/portland",
    'pricing': "medium",
    'phone-number': "(503) 796-2739",
    'address': "206 SW Morrison St, Portland, OR 97204",
    'other-amenities': ['outdoor-seating', 'gluten-free-options', 'games'],
    'has-drink': "true",
    'has-food': "true",
  }
]
