{
  'name': "Base Camp Brewery",
  'area': "se",
  'hours': {
    'friday-end': "6",
    'friday-start': "3",
    'monday-end': "10",
    'monday-start': "0",
    'saturday-end': "3",
    'saturday-start': "0",
    'sunday-end': "3",
    'sunday-start': "0",
    'thursday-end': "6",
    'thursday-start': "3",
    'tuesday-end': "6",
    'tuesday-start': "3",
    'wednesday-end': "6",
    'wednesday-start': "3"
  }
  'description': "$1 off pints",
  'link': "https://basecampbrewingco.com/",
  'pricing': "medium",
  'phone-number': "503-477-7479",
  'address': "930 SE Oak St, Portland, OR 97214",
  'other-amenities': ['outdoor-seating', 'trivia'],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "Bartini",
  'area': "nw",
  'hours': {
    'monday-start': "4",
    'monday-end': "6",
    'tuesday-start': "4",
    'tuesday-end': "6",
    'wednesday-start': "4"
    'wednesday-end': "6",
    'thursday-start': "4",
    'thursday-end': "6",
    'friday-start': "4",
    'friday-end': "6",
    'saturday-start': "4",
    'saturday-end': "6",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "About 50% off food, $4-$6 drinks.",
  'link': "http://www.bartinipdx.com/",
  'pricing': "medium",
  'phone-number': "503-224-7919",
  'address': "2108 NW Glisan St, Portland, OR 97210",
  'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "",
  'area': "",
  'hours': {
    'monday-start': "",
    'monday-end': "",
    'tuesday-start': "",
    'tuesday-end': "",
    'wednesday-start': ""
    'wednesday-end': "",
    'thursday-start': "",
    'thursday-end': "",
    'friday-start': "",
    'friday-end': "",
    'saturday-start': "",
    'saturday-end': "",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "",
  'link': "",
  'pricing': "",
  'phone-number': "",
  'address': "",
  'other-amenities': [''],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "",
  'area': "",
  'hours': {
    'monday-start': "",
    'monday-end': "",
    'tuesday-start': "",
    'tuesday-end': "",
    'wednesday-start': ""
    'wednesday-end': "",
    'thursday-start': "",
    'thursday-end': "",
    'friday-start': "",
    'friday-end': "",
    'saturday-start': "",
    'saturday-end': "",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "",
  'link': "",
  'pricing': "",
  'phone-number': "",
  'address': "",
  'other-amenities': [''],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "",
  'area': "",
  'hours': {
    'monday-start': "",
    'monday-end': "",
    'tuesday-start': "",
    'tuesday-end': "",
    'wednesday-start': ""
    'wednesday-end': "",
    'thursday-start': "",
    'thursday-end': "",
    'friday-start': "",
    'friday-end': "",
    'saturday-start': "",
    'saturday-end': "",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "",
  'link': "",
  'pricing': "",
  'phone-number': "",
  'address': "",
  'other-amenities': [''],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "",
  'area': "",
  'hours': {
    'monday-start': "",
    'monday-end': "",
    'tuesday-start': "",
    'tuesday-end': "",
    'wednesday-start': ""
    'wednesday-end': "",
    'thursday-start': "",
    'thursday-end': "",
    'friday-start': "",
    'friday-end': "",
    'saturday-start': "",
    'saturday-end': "",
    'sunday-start': "4",
    'sunday-end': "11",
  }
  'description': "",
  'link': "",
  'pricing': "",
  'phone-number': "",
  'address': "",
  'other-amenities': [''],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "Punch Bowl Social",
  'area': "NW",
  'hours': {
    'monday-start': "3",
    'monday-end': "6",
    'tuesday-start': "3",
    'tuesday-end': "6",
    'wednesday-start': "3"
    'wednesday-end': "6",
    'thursday-start': "3",
    'thursday-end': "6",
    'friday-start': "3",
    'friday-end': "6",
    'saturday-start': "3",
    'saturday-end': "6",
    'sunday-start': "3",
    'sunday-end': "6",
  }
  'description': "$2 - $6 food, $3 - $7 drinks",
  'link': "http://www.punchbowlsocial.com/location/portland",
  'pricing': "medium",
  'phone-number': "(503) 334-0360",
  'address': "340 SW Morrison St, Portland, OR 97204",
  'other-amenities': ['outdoor-seating', 'games', 'karaoke', 'vegan-options', 'gluten-free-options'],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "Santa Fe Taqueria",
  'area': "NW",
  'hours': {
    'monday-start': "11",
    'monday-end': "12",
    'tuesday-start': "11",
    'tuesday-end': "12",
    'wednesday-start': "11"
    'wednesday-end': "12",
    'thursday-start': "11",
    'thursday-end': "12",
    'friday-start': "11",
    'friday-end': "12",
    'saturday-start': "11",
    'saturday-end': "12",
    'sunday-start': "11",
    'sunday-end': "12",
  }
  'description': "50% off food menu",
  'link': "http://www.santafetaqueria.com/index.php/menu",
  'pricing': "low",
  'phone-number': "(503) 220-0406",
  'address': "831 NW 23rd Ave, Portland, OR 97210",
  'other-amenities': ['outdoor-seating', 'vegan-options', 'gluten-free-options'],
  'has-drink': "false",
  'has-food': "true",
},
{
  'name': "Pearl Tavern",
  'area': "SW",
  'hours': {
    'monday-start': "3",
    'monday-end': "6",
    'tuesday-start': "3",
    'tuesday-end': "6",
    'wednesday-start': "3"
    'wednesday-end': "6",
    'thursday-start': "3",
    'thursday-end': "6",
    'friday-start': "3",
    'friday-end': "6",
    'saturday-start': "3",
    'saturday-end': "6",
    'sunday-start': "3",
    'sunday-end': "6",
  }
  'description': "$4 - $10 food, $6 - $8 cocktails",
  'link': "http://pearltavernpdx.com/wp-content/uploads/2017/05/Happy-Hour-5.4.17-1.pdf",
  'pricing': "high",
  'phone-number': "(503) 954-3796",
  'address': "231 NW 11th Ave, Portland, OR 97209",
  'other-amenities': ['vegan-options', 'gluten-free-options'],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "Headwaters",
  'area': "SW",
  'hours': {
    'monday-start': "0",
    'monday-end': "6",
    'tuesday-start': "0",
    'tuesday-end': "6",
    'wednesday-start': "0"
    'wednesday-end': "6",
    'thursday-start': "0",
    'thursday-end': "6",
    'friday-start': "0",
    'friday-end': "6",
    'saturday-start': "10",
    'saturday-end': "12",
    'sunday-start': "10",
    'sunday-end': "12",
  }
  'description': "$7 - $9 fancy food, $5 cocktails",
  'link': "http://www.headwaterspdx.com/s/Happy-Hour-41517-1-xces.pdf",
  'pricing': "high",
  'phone-number': "(503) 790-7752",
  'address': "1001 SW Broadway, Portland, OR 97205",
  'other-amenities': [''],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "Shift Drinks",
  'area': "SW",
  'hours': {
    'monday-start': "4",
    'monday-end': "20",
    'tuesday-start': "4",
    'tuesday-end': "20",
    'wednesday-start': "4"
    'wednesday-end': "20",
    'thursday-start': "4",
    'thursday-end': "20",
    'friday-start': "4",
    'friday-end': "20",
    'saturday-start': "4",
    'saturday-end': "20",
    'sunday-start': "4",
    'sunday-end': "20",
  }
  'description': "Cheaper smaller portions of usually expensive food",
  'link': "https://www.scribd.com/document/348549641/Shift-Drinks-Happy-Hour-Menu-05-16-17",
  'pricing': "medium",
  'phone-number': "(503) 922-3933",
  'address': "1200 SW Morrison St, Portland, OR 97205",
  'other-amenities': ['vegan-options'],
  'has-drink': "true",
  'has-food': "true",
},
{
  'name': "Red Star Tavern",
  'area': "SW",
  'hours': {
    'monday-start': "4",
    'monday-end': "7",
    'tuesday-start': "4",
    'tuesday-end': "7",
    'wednesday-start': "4"
    'wednesday-end': "7",
    'thursday-start': "4",
    'thursday-end': "7",
    'friday-start': "4",
    'friday-end': "7",
    'saturday-start': "4",
    'saturday-end': "7",
    'sunday-start': "4",
    'sunday-end': "7",
  }
  'description': "Happy hour food ONLY, $2 - $6",
  'link': "http://www.redstartavern.com/menus/menus.htm",
  'pricing': "medium",
  'phone-number': "(503) 222-0005",
  'address': "503 SW Alder St, Portland, OR 97204",
  'other-amenities': ['gluten-free-options', 'vegan-options'],
  'has-drink': "false",
  'has-food': "true",
},
